apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}
  labels:
{{ include "guacamole.labels" . | indent 4 }}
type: Opaque
data:
  GUACD_HOSTNAME: {{ printf "%s-%s" (include "guacamole.name" .) "guacd" | b64enc | quote }}
  GUACD_PORT: {{ "4822" | b64enc | quote }}
  POSTGRESQL_HOSTNAME: {{ .Values.postgres.hostname | b64enc | quote }}
  POSTGRESQL_PORT: {{ .Values.postgres.port | b64enc | quote }}
  POSTGRESQL_DATABASE: {{ .Values.postgres.database | b64enc | quote }}
  POSTGRESQL_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
{{- if .Values.OIDC }}
  OPENID_AUTHORIZATION_ENDPOINT: {{ .Values.OIDC.authorization_endpoint | b64enc | quote }}
  OPENID_JWKS_ENDPOINT: {{ .Values.OIDC.jwks_endpoint | b64enc | quote }}
  OPENID_ISSUER: {{ .Values.OIDC.issuer | b64enc | quote }}
  OPENID_CLIENT_ID: {{ .Values.OIDC.clientID | b64enc | quote }}
  OPENID_REDIRECT_URI: {{ .Values.OIDC.redirect_uri | b64enc | quote }}
  {{- if .Values.OIDC.username_claim_type }}
  OPENID_USERNAME_CLAIM_TYPE: {{ .Values.OIDC.username_claim_type | b64enc | quote }}
  {{- end }}
  {{- if .Values.OIDC.groups_claim_type }}
  OPENID_GROUPS_CLAIM_TYPE: {{ .Values.OIDC.groups_claim_type | b64enc | quote }}
  {{- end }}
{{- end }}

{{- if .Values.extension_priority }}
  EXTENSION_PRIORITY: {{ .Values.extension_priority | b64enc | quote }}
{{- end }}

  ADMIN_USERNAME: {{ .Values.dbcreation.adminUsername | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.dbcreation.adminLocalPassword | b64enc | quote }}
